apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: staticroutes.networking.digitalocean.com
spec:
  group: networking.digitalocean.com
  names:
    kind: StaticRoute
    plural: staticroutes
    shortNames:
    - sr
    singular: staticroute
  scope: Cluster
  versions:
  - additionalPrinterColumns:
    - jsonPath: .metadata.creationTimestamp
      name: Age
      priority: 0
      type: date
    - description: Destination host(s)/subnet(s)
      jsonPath: .spec.destinations
      name: Destinations
      priority: 1
      type: string
    - description: Gateway to route through
      jsonPath: .spec.gateway
      name: Gateway
      priority: 1
      type: string
    - description: Label to discover deployment pods to route through instead of a
        dedicated Gateway
      jsonPath: .spec.deploymentlabel
      name: DeploymentLabel
      priority: 1
      type: string
    name: v1
    schema:
      openAPIV3Schema:
        properties:
          spec:
            properties:
              deploymentlabel:
                default: default-label
                description: Label to discover deployment pods to route through instead
                  of a dedicated Gateway
                pattern: ^([a-z0-9\.\-]+)$
                type: string
              destinations:
                description: Destination host(s)/subnet(s) to route through the gateway
                  (required)
                items:
                  pattern: ^([0-9]{1,3}\.){3}[0-9]{1,3}$|^([0-9]{1,3}\.){3}[0-9]{1,3}(\/([0-9]|[1-2][0-9]|3[0-2]))?$
                  type: string
                type: array
              gateway:
                default: 0.0.0.0
                description: Gateway to route through
                pattern: ^([0-9]{1,3}\.){3}[0-9]{1,3}$
                type: string
            required:
            - destinations
            type: object
          status:
            type: object
            x-kubernetes-preserve-unknown-fields: true
        type: object
    served: true
    storage: true
