---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: k8s-staticroute-operator
rules:
  # Framework: knowing which other operators are running (i.e. peering).
  - apiGroups: [networking.digitalocean.com]
    resources: [clusterkopfpeerings]
    verbs: [list, watch, patch, get]
    
  # Framework: runtime observation of namespaces & CRDs (addition/deletion).
  - apiGroups: [apiextensions.k8s.io]
    resources: [customresourcedefinitions]
    verbs: [list, watch]
    
  - apiGroups: [""]
    resources: [namespaces]
    verbs: [list, watch]

  # Framework: posting the events about the handlers progress/errors.
  - apiGroups: [""]
    resources: [events]
    verbs: [create]

  # Application: watching & handling for the custom resource we declare.
  - apiGroups: [networking.digitalocean.com]
    resources: [staticroutes]
    verbs: [list, watch, patch]

  - apiGroups: [""]
    resources: [pods]
    verbs: [list, get]
  
  # - apiGroups: [""]
  #   resources: [services]
  #   verbs: [list, watch, get]
    
  # - apiGroups: [extensions,apps]
  #   resources: [deployments,replicasets]
  #   verbs: [list, watch, get]
